//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardAccessPeer) DeepCopyInto(out *WireguardAccessPeer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(WireguardAccessPeerStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardAccessPeer.
func (in *WireguardAccessPeer) DeepCopy() *WireguardAccessPeer {
	if in == nil {
		return nil
	}
	out := new(WireguardAccessPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireguardAccessPeer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardAccessPeerList) DeepCopyInto(out *WireguardAccessPeerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireguardAccessPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardAccessPeerList.
func (in *WireguardAccessPeerList) DeepCopy() *WireguardAccessPeerList {
	if in == nil {
		return nil
	}
	out := new(WireguardAccessPeerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireguardAccessPeerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardAccessPeerSpec) DeepCopyInto(out *WireguardAccessPeerSpec) {
	*out = *in
	if in.AccessRules != nil {
		in, out := &in.AccessRules, &out.AccessRules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardAccessPeerSpec.
func (in *WireguardAccessPeerSpec) DeepCopy() *WireguardAccessPeerSpec {
	if in == nil {
		return nil
	}
	out := new(WireguardAccessPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardAccessPeerStatus) DeepCopyInto(out *WireguardAccessPeerStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]WireguardAccessPeerStatusPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardAccessPeerStatus.
func (in *WireguardAccessPeerStatus) DeepCopy() *WireguardAccessPeerStatus {
	if in == nil {
		return nil
	}
	out := new(WireguardAccessPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardAccessPeerStatusPeer) DeepCopyInto(out *WireguardAccessPeerStatusPeer) {
	*out = *in
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardAccessPeerStatusPeer.
func (in *WireguardAccessPeerStatusPeer) DeepCopy() *WireguardAccessPeerStatusPeer {
	if in == nil {
		return nil
	}
	out := new(WireguardAccessPeerStatusPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardAccessRule) DeepCopyInto(out *WireguardAccessRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardAccessRule.
func (in *WireguardAccessRule) DeepCopy() *WireguardAccessRule {
	if in == nil {
		return nil
	}
	out := new(WireguardAccessRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireguardAccessRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardAccessRuleList) DeepCopyInto(out *WireguardAccessRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireguardAccessRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardAccessRuleList.
func (in *WireguardAccessRuleList) DeepCopy() *WireguardAccessRuleList {
	if in == nil {
		return nil
	}
	out := new(WireguardAccessRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireguardAccessRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardAccessRuleSpec) DeepCopyInto(out *WireguardAccessRuleSpec) {
	*out = *in
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardAccessRuleSpec.
func (in *WireguardAccessRuleSpec) DeepCopy() *WireguardAccessRuleSpec {
	if in == nil {
		return nil
	}
	out := new(WireguardAccessRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardClusterClient) DeepCopyInto(out *WireguardClusterClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(WireguardClusterClientStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardClusterClient.
func (in *WireguardClusterClient) DeepCopy() *WireguardClusterClient {
	if in == nil {
		return nil
	}
	out := new(WireguardClusterClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireguardClusterClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardClusterClientList) DeepCopyInto(out *WireguardClusterClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireguardClusterClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardClusterClientList.
func (in *WireguardClusterClientList) DeepCopy() *WireguardClusterClientList {
	if in == nil {
		return nil
	}
	out := new(WireguardClusterClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireguardClusterClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardClusterClientNode) DeepCopyInto(out *WireguardClusterClientNode) {
	*out = *in
	out.PrivateKey = in.PrivateKey
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardClusterClientNode.
func (in *WireguardClusterClientNode) DeepCopy() *WireguardClusterClientNode {
	if in == nil {
		return nil
	}
	out := new(WireguardClusterClientNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardClusterClientNodePrivateKey) DeepCopyInto(out *WireguardClusterClientNodePrivateKey) {
	*out = *in
	out.SecretRef = in.SecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardClusterClientNodePrivateKey.
func (in *WireguardClusterClientNodePrivateKey) DeepCopy() *WireguardClusterClientNodePrivateKey {
	if in == nil {
		return nil
	}
	out := new(WireguardClusterClientNodePrivateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardClusterClientSpec) DeepCopyInto(out *WireguardClusterClientSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]WireguardClusterClientNode, len(*in))
		copy(*out, *in)
	}
	out.Server = in.Server
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardClusterClientSpec.
func (in *WireguardClusterClientSpec) DeepCopy() *WireguardClusterClientSpec {
	if in == nil {
		return nil
	}
	out := new(WireguardClusterClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardClusterClientSpecServer) DeepCopyInto(out *WireguardClusterClientSpecServer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardClusterClientSpecServer.
func (in *WireguardClusterClientSpecServer) DeepCopy() *WireguardClusterClientSpecServer {
	if in == nil {
		return nil
	}
	out := new(WireguardClusterClientSpecServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireguardClusterClientStatus) DeepCopyInto(out *WireguardClusterClientStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireguardClusterClientStatus.
func (in *WireguardClusterClientStatus) DeepCopy() *WireguardClusterClientStatus {
	if in == nil {
		return nil
	}
	out := new(WireguardClusterClientStatus)
	in.DeepCopyInto(out)
	return out
}
