{{ if .Values.clusterClient.enable }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wgc
  labels:
    app: wireguardclusterclient
spec:
  selector:
      matchLabels:
        app: wireguardclusterclient
  template:
    metadata:
      labels:
        app: wireguardclusterclient
    spec:
      serviceAccountName: {{include "wga.serviceAccountName" .}}
      hostNetwork: true
      containers:
        - image: "{{- .Values.global.imageRegistry }}/{{- .Values.endpoint.image.name -}}:{{- default .Chart.AppVersion .Values.endpoint.image.tag }}"
          {{- if.Values.endpoint.image.pullPolicy }}
          imagePullPolicy: {{.Values.endpoint.image.pullPolicy }}
          {{- end }}
          name: wgc
          args:
            - clusterclient
          resources:
            {{- toYaml .Values.clusterClient.resources | nindent 12 }}
          env:
          {{- if and .Values.clusterClient.resources.limits .Values.clusterClient.resources.limits.memory -}}
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: wgc
                  resource: limits.memory
          {{- end }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      restartPolicy: Always
{{ end }}
