---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint
stringData:
  privateKey:     {{ ( include "gen.endpoint.privateKey" . )  }} 
  endpoint.yaml: |
{{ .Values.endpoint | toYaml | indent 4 }}

