---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint
data:
  privateKey:     {{ ( include "gen.endpoint.privateKey" . )  | b64enc  }} 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: endpoint
data:
  endpoint.yaml: |
{{ .Values.endpoint | toYaml | indent 4 }}
  run.yaml:  |
{{ ( include "gen.endpoint.peers" . ) | indent 4 }}
