---
apiVersion: v1
kind: Secret
metadata:
  name: config
data:
  config.json: {{ .Values.config | mustToJson | b64enc }}
  nftables.conf: {{.Values.nftables | b64enc }}
  sysctl.conf: {{.Values.sysctl | b64enc }}
