---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint
data:
  privateKey:     {{ ( include "gen.endpoint.privateKey" . )  }} 
  endpoint.yaml: |
{{ .Values.endpoint | toYaml | indent 4 }}



{{- $runconfig := lookup "v1" "ConfigMap" .Release.Namespace "run" -}}
{{- if $runconfig -}}
{{- else -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: run
data:
  run.yaml:  |
    ---
{{- end -}}
