---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      serviceAccountName: {{include "wga.serviceAccountName" .}}
      containers:
        - image: "{{ .Values.image.repository }}:{{include "wga.imageTag" .}}"
          imagePullPolicy: IfNotPresent
          name: wg
          args:
            - ep
          ports:
            - containerPort: {{.Values.endpoint.port}}
              name: wireguard
              protocol: UDP
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: WGA_CLIENT_CIDR
              value: {{.Values.endpoint.clientCIDR}}
            - name: WGA_SERVER_ADDRESS
              value: {{.Values.endpoint.address}}
            - name: WGA_ALLOWED_IPS
              value: {{join "," .Values.endpoint.allowedIPs}}
              {{- if .Values.logLevel }}
            - name: LOG_LEVEL
              value: "{{ .Values.logLevel }}"
              {{- end }}
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: wg
                  resource: limits.memory
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - mountPath: /etc/wga/endpoint/
              name: endpoint
      restartPolicy: Always
      volumes:
        - name: endpoint
          secret:
            defaultMode: 420
            secretName: endpoint
