---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wireguard
    spec:
      containers:
      - image: ghcr.io/kraudcloud/wga:${{.Values.version }}}
        imagePullPolicy: IfNotPresent
        name: wg
        ports:
        - containerPort: {{. Values.port }}
          name: wireguard
          protocol: UDP
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /etc/wireguard/
          name: config
      restartPolicy: Always
      securityContext: {}
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: config
