---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    spec:
      containers:
      - image: ghcr.io/kraudcloud/wga:{{.Values.version }}
        imagePullPolicy: IfNotPresent
        name: wg
        args:
          - ep
        ports:
        - containerPort: {{ .Values.port }}
          name: wireguard
          protocol: UDP
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: wg
                resource: limits.memory
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /etc/wga/privateKey
          name: endpoint
          subPath: privateKey
        - mountPath: /etc/wga/endpoint.yaml
          name: config
          subPath: endpoint.yaml
        - mountPath: /etc/wga/run.yaml
          name: run
          subPath: run.yaml
      restartPolicy: Always
      volumes:
      - name: endpoint
        secret:
          defaultMode: 420
          secretName: endpoint
      - name: run
        configMap:
          defaultMode: 420
          name: run
