---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wireguard
    spec:
      containers:
      - image: ghcr.io/kraudcloud/wga:{{.Values.version }}
        imagePullPolicy: IfNotPresent
        name: wg
        args:
          - ep
        ports:
        - containerPort: {{ .Values.port }}
          name: wireguard
          protocol: UDP
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: wg
                resource: limits.memory
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /etc/wga/privateKey
          name: secrets
          subPath: privateKey
        - mountPath: /etc/wga/static.yaml
          name: config
          subPath: static.yaml
        - mountPath: /etc/wga/peers.yaml
          name: config
          subPath: peers.yaml
      restartPolicy: Always
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: endpoint
      - name: config
        configMap:
          defaultMode: 420
          name: endpoint
