apiVersion: v1
kind: Service
metadata:
  name: wg
  annotations:
    {{.Values.service.annotations | toYaml | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.port }}
    protocol: UDP
    targetPort: {{ .Values.port }}
  selector:
    app: wireguard
