apiVersion: v1
kind: Service
metadata:
  name: wg
  annotations:
    {{.Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{. Values.port }}
    protocol: UDP
    targetPort: {{. Values.port }}
  selector:
    app: wireguard
