# Because wga needs to access the Kubernetes API, we need to grant it access to do so.
# It needs access to at least list and watch the WireguardAccessRule and WireguardAccessPeer CRDs.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wga.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wga.fullname" . }}:controller
rules:
- apiGroups: ["wga.kraudcloud.com"]
  resources: ["wireguardaccessrules", "wireguardaccesspeers"]
  verbs: ["*"] # Note: we could restrict to `["list", "watch"]` for now, but it's likely we'll need to change this later.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wga.fullname" . }}:controller
subjects:
- kind: ServiceAccount
  name: {{ include "wga.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "wga.fullname" . }}:controller
  apiGroup: rbac.authorization.k8s.io
