---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wga.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "wga.labels" . | nindent 4}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wga.fullname" . }}:controller
  labels: {{- include "wga.labels" . | nindent 4}}
rules:
- apiGroups: ["wga.kraudcloud.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services", "services/status", "secrets", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# edit node labels
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wga.fullname" . }}:controller
  labels: {{- include "wga.labels" . | nindent 4}}
subjects:
- kind: ServiceAccount
  name: {{ include "wga.fullname" . }}
  namespace: {{.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "wga.fullname" . }}:controller
  apiGroup: rbac.authorization.k8s.io