service:
  type: "LoadBalancer" 
  annotations: {}

port: 51820

version: "latest"

config: |
  [Interface]
  Address = 172.27.1.200/24
  PrivateKey = GF1XfJZLrDuCuvXy9mB6PUkqM19w93S5sWD3wteVYUU=
  ListenPort = 51820
  
  [Peer]
  PublicKey = mDtPzUAay7AX0Fi76swpy9gpY8TSBknyQ4cX7cP0nXE=
  AllowedIPs = 172.27.1.11/32
