## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
global:
  imageRegistry: "ghcr.io/kraudcloud"

## @section Common parameters
##

## @param endpoint.clientCIDR CIDR range for client IPs. This is the range from which the wga pod will allocate IPs.
## @param endpoint.address Public address for the wireguard interface. Prefer using endpoint.service.loadBalancerIP
## @param endpoint.allowedIPs List of IPs that are allowed to connect to from the wireguard interface
## @param endpoint.logLevel Log level for the wireguard interface. error: 8, warn: 4, info: 0, debug: -4
## @param endpoint.annotations Additional annotations for the wireguard interface
## @param endpoint.labels Additional labels for the wireguard interface
##
endpoint:
  clientCIDR: ""
  address: ""
  allowedIPs: ""
  logLevel: 0
  annotations: {}
  labels: {}

  ## @param endpoint.service.type Kubernetes Service type.
  ## @param endpoint.service.loadBalancerClass Kubernetes LoadBalancerClass to use
  ## @param endpoint.service.loadBalancerIP Kubernetes LoadBalancerIP to use
  ## @param endpoint.service.port Kubernetes Service port
  ## @param endpoint.service.annotations Additional annotations for the Service
  ## @param endpoint.service.labels Additional labels for the Service
  ##
  service:
    type: "LoadBalancer"
    loadBalancerClass: ""
    loadBalancerIP: ""
    port: 51820
    annotations: {}
    labels: {}

  ## @param endpoint.image.name endpoint image name
  ## @param endpoint.image.tag endpoint image tag
  ## @param endpoint.image.pullPolicy Image pull policy
  ##
  image:
    name: wga
    tag: ""
    pullPolicy: ""

  ## @param endpoint.resources.requests.memory Memory requests for the container
  ## @param endpoint.resources.limits.memory Memory limits for the container
  ## @param endpoint.resources.requests.cpu CPU requests for the container
  ## @param endpoint.resources.limits.cpu CPU limits for the container
  ##
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "128Mi"
      cpu: "500m"

## @param serviceAccount.create Specifies whether a service account should be created. A service is required for the wga to communicate with the Kubernetes API.
## @param serviceAccount.name The name of the service account to use. If not set and create is true, a name is generated using the fullname template.
##
serviceAccount:
  create: true
  name: ""
