service:
  type: "LoadBalancer"
  loadBalancerClass: null
  loadBalancerIP: null
  annotations: {}

port: 51820

version: "0.3.21"

endpoint:
  clientCIDR: fdfd::/16

serviceAccount:
  create: true
  name:
