{{- if .Values.unbound.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wga-unbound
  labels:
    app: wga-unbound
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wga-unbound
  template:
    metadata:
      labels:
        app: wga-unbound
    spec:
      restartPolicy: Always
      containers:
        - image: "{{ include "wga.endpointImage" . }}"
          name: unbound
          command:
            - /usr/sbin/unbound
            - -dvvv
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
        - image: "{{- .Values.unbound.welcomeImage.name -}}:{{- .Values.unbound.welcomeImage.tag }}"
          name: wga-welcome
          imagePullPolicy: {{.Values.unbound.welcomeImage.pullPolicy }}
          ports:
            - containerPort: 80
              name: welcome
              protocol: TCP
{{- end}}
