{{- if .Values.unbound.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: wga-unbound
  annotations: {{ .Values.unbound.service.annotations | toYaml | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerClass: wga
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
    name: dns
  - port: 80
    protocol: TCP
    targetPort: 80
    name: welcome
  selector:
    app: wga-unbound
{{- end }}
