{{- if .Values.unbound.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: wga-unbound
  annotations:
    metallb.universe.tf/loadBalancerIPs: "{{ .Values.unbound.ip }}"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerClass: wga
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wga-unbound
{{- end }}
