apiVersion: v1
kind: Secret
metadata:
  name: wga-web-secret
  labels:
    {{- include "wga.labels" . | nindent 4 -}}
    {{- if .Values.web.labels }}
    {{- toYaml .Values.web.labels | nindent 4 -}}
    {{- end }}
    app: wga-web
  {{- if .Values.web.annotations }}
  annotations:
  {{- .Values.web.annotations | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
data:
  authentik-secret: {{ .Values.web.authSecret | b64enc | quote}}
  auth-secret: {{ randAlphaNum 64 | b64enc | quote }}