apiVersion: v1
kind: Service
metadata:
  name: wga-web
  labels:
    {{- include "wga.labels" . | nindent 4 -}}
    {{- if .Values.web.labels }}
    {{- toYaml .Values.web.labels | nindent 4 -}}
    {{- end }}
    app: wga-web
  {{- if .Values.web.annotations }}
  annotations:
  {{- .Values.web.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: wga-web