apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wireguardaccessrules.wga.kraudcloud.com
spec:
  group: wga.kraudcloud.com
  versions:
  - name: v1beta
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              destinations:
                type: array
                items:
                  type: string
                description: List of destination IP addresses or CIDRs
            required:
            - destinations
        required:
        - spec
    additionalPrinterColumns:
    - name: Destinations
      type: string
      description: List of destination IP addresses or CIDRs
      jsonPath: .spec.destinations
  scope: Cluster
  names:
    plural: wireguardaccessrules
    singular: wireguardaccessrule
    kind: WireguardAccessRule
    shortNames:
    - wgar
    - wgars
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wireguardaccesspeers.wga.kraudcloud.com
spec:
  group: wga.kraudcloud.com
  versions:
  - name: v1beta
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              preSharedKey:
                type: string
                pattern: ^[A-Za-z0-9+/=]+$
                description: Pre-shared key
              publicKey:
                type: string
                pattern: ^[A-Za-z0-9+/=]+$
                description: Public key
              accessRules:
                type: array
                items:
                  type: string
                description: List of access roles
            required:
            - publicKey
            - accessRules
          status:
            type: object
            properties:
              lastUpdated:
                type: string
                description: Last update time
                format: date-time
              address:
                type: string
                description: Address of the "client" peer
              peers:
                type: array
                items:
                  type: object
                  properties:
                    endpoint:
                      type: string
                      description: Endpoint of the "server" peer
                    preSharedKey:
                      type: string
                      description: Pre-shared key
                      pattern: ^[A-Za-z0-9+/=]+$
                    publicKey:
                      type: string
                      description: Public key
                      pattern: ^[A-Za-z0-9+/=]+$
                    allowedIPs:
                      type: array
                      items:
                        type: string
                        description: Allowed IP addresses or CIDRs
                  required:
                  - endpoint
                  - publicKey
                  - allowedIPs
            required:
            - lastUpdated
            - address
            - peers
        required:
        - spec
    additionalPrinterColumns:
    - name: Address
      type: string
      description: Address of the "client" peer
      jsonPath: .status.address
    - name: "Last Updated"
      type: string
      description: Last update time
      jsonPath: .status.lastUpdated
  scope: Cluster
  names:
    plural: wireguardaccesspeers
    singular: wireguardaccesspeer
    kind: WireguardAccessPeer
    shortNames:
    - wgap
    - wgaps
