name: publish
on: [push]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image
        run: |
          docker build . --tag ghcr.io/kraudcloud/wga:latest
          docker push ghcr.io/kraudcloud/wga:latest

      - name: Install helm
        uses: azure/setup-helm@v3

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: wga
          repository: kraudcloud
          tag: 0.1.0-chart
          path: charts/wga
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
