name: publish
on:
  push:
    tags:
      - '*'
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image
        run: |
          docker build . --tag ghcr.io/kraudcloud/wga:${{github.ref_name}}
          docker push ghcr.io/kraudcloud/wga:${{github.ref_name}}

  publish-helm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install helm
        uses: azure/setup-helm@v3

      - name: inject build tag into helm
        run: |
          sed -i 's/version: "latest"/version: "${{github.ref_name}}"/' charts/wga/values.yaml
          sed -i 's/appVersion: "latest"/appVersion: "${{github.ref_name}}"/' charts/wga/Chart.yaml

      - name: push chart
        env:
          HELM_EXPERIMENTAL_OCI: 1
        run : |
          echo '${{ secrets.GITHUB_TOKEN }}' | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
          helm package charts/wga --version ${{github.ref_name}}-chart
          helm push wga-${{github.ref_name}}-chart.tgz oci://ghcr.io/kraudcloud
