name: CI

on:
  push:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run helm unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
          helm unittest charts/wga
